name: Gold Price Auto Update

on:
  schedule:
    - cron: '*/2 * * * *' # every 2 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libxss1 libgtk-3-0 libgbm1 libnss3

      - name: Install NPM
        run: npm install

      - name: Run Scraper
        run: node index.js

      # ðŸ‘‡ THIS MAKES JSON PERMANENT
      - name: Commit & Push result.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add result.json
          git commit -m "update gold price" || echo "No changes"
          git push
env:
  FORCE_RUN: 1